package com.devinsight.domain.model;

/**
 * Distinguishes the origin of a piece of feedback attached to an analysis.
 *
 * AI         - Generated by an AI/LLM model (e.g. OpenAI, Gemini).
 * RULE_BASED - Generated by deterministic rules evaluated against metric thresholds.
 */
public enum FeedbackType {
    AI,
    RULE_BASED
}
