#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: DevInsight → Azure Container Apps (API) + GitHub Pages (SPA).
# Run from the repository root:  bash scripts/setup-azure.sh
# ──────────────────────────────────────────────────────────────────────────

ENV_FILE="${DEVINSIGHT_ENV_FILE:-.env.azure}"   # local only (git-ignored); deliberately not the local-dev .env
REPO="CMaintz/dev-insight"
FRONTEND_URL="https://cmaintz.github.io/dev-insight"
IMAGE="ghcr.io/cmaintz/devinsight-api:latest"
TOTAL_STAGES=9

# deploy_infra runs the Bicep template with the values captured so far and sets API_URL.
deploy_infra() {
  export DEVINSIGHT_IMAGE="$1"
  export DEVINSIGHT_DEPLOY_POSTGRES DEVINSIGHT_DB_CONNECTION DEVINSIGHT_DB_PASSWORD
  export DEVINSIGHT_GITHUB_CLIENT_ID DEVINSIGHT_GITHUB_CLIENT_SECRET DEVINSIGHT_JWT_SIGNING_KEY DEVINSIGHT_ANTHROPIC_API_KEY
  say "Deploying (PostgreSQL takes 5-10 minutes the first time)..."
  API_URL=$(az deployment group create \
    --resource-group "$AZURE_RESOURCE_GROUP" \
    --template-file infra/main.bicep \
    --parameters infra/main.bicepparam \
    --query properties.outputs.apiUrl.value --output tsv)
  printf '  %s✓ API URL%s %s\n' "$GREEN" "$RESET" "$API_URL"
}

banner "DevInsight: Azure + GitHub Pages setup"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Azure CLI and sign-in"
say "You need an Azure account (a new free account includes 12 months of free PostgreSQL)."
if ! command -v az >/dev/null 2>&1; then
  warn "Azure CLI not found. Install it, open a NEW terminal, and re-run this wizard:"
  note "  winget install --exact --id Microsoft.AzureCLI"
  open_url "https://learn.microsoft.com/cli/azure/install-azure-cli"
  exit 1
fi
if ! az account show >/dev/null 2>&1; then
  step "A browser window opens for the Azure sign-in."
  az login --output none
fi
AZURE_SUBSCRIPTION_ID=$(az account show --query id -o tsv)
AZURE_TENANT_ID=$(az account show --query tenantId -o tsv)
say "Signed in to subscription: $(az account show --query name -o tsv)"
if ! confirm "Deploy into this subscription?"; then
  warn "Switch with: az account set --subscription <id>, then re-run."
  exit 1
fi
write_env AZURE_SUBSCRIPTION_ID "$AZURE_SUBSCRIPTION_ID"
write_env AZURE_TENANT_ID "$AZURE_TENANT_ID"
for provider in Microsoft.App Microsoft.OperationalInsights Microsoft.DBforPostgreSQL; do
  az provider register --namespace "$provider" --wait --output none
done
printf '  %s✓%s resource providers registered\n' "$GREEN" "$RESET"
pause

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Resource group"
say "Everything lives in one resource group; deleting the group removes all of it."
ask AZURE_RESOURCE_GROUP "Resource group name (e.g. rg-devinsight):"
ask AZURE_LOCATION "Azure region (e.g. northeurope, swedencentral):"
az group create --name "$AZURE_RESOURCE_GROUP" --location "$AZURE_LOCATION" --output none
write_env AZURE_RESOURCE_GROUP "$AZURE_RESOURCE_GROUP"
write_env AZURE_LOCATION "$AZURE_LOCATION"
pause

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Database and app secrets"
say "Option A: Azure Database for PostgreSQL (free for 12 months on a free account, then about USD 13/month)."
say "Option B: bring your own PostgreSQL (Supabase or Neon free tier) as a connection string."
if confirm "Use Azure Database for PostgreSQL (option A)?"; then
  DEVINSIGHT_DEPLOY_POSTGRES=true
  DEVINSIGHT_DB_CONNECTION=""
  DEVINSIGHT_DB_PASSWORD=$(_existing DEVINSIGHT_DB_PASSWORD || true)
  if [[ -z "$DEVINSIGHT_DB_PASSWORD" ]]; then
    DEVINSIGHT_DB_PASSWORD="Di$(openssl rand -hex 20)!"
  fi
  note "Using a generated strong admin password (saved to $ENV_FILE)."
else
  DEVINSIGHT_DEPLOY_POSTGRES=false
  DEVINSIGHT_DB_PASSWORD=""
  step "Supabase: Project > Connect > Session pooler > .NET tab.  Neon: Dashboard > Connection string (.NET)."
  ask_secret DEVINSIGHT_DB_CONNECTION "Paste the Npgsql connection string (Host=...;Database=...;Username=...;Password=...;SSL Mode=Require):"
fi
write_env DEVINSIGHT_DEPLOY_POSTGRES "$DEVINSIGHT_DEPLOY_POSTGRES"
write_env DEVINSIGHT_DB_PASSWORD "$DEVINSIGHT_DB_PASSWORD"
write_env DEVINSIGHT_DB_CONNECTION "$DEVINSIGHT_DB_CONNECTION"
DEVINSIGHT_JWT_SIGNING_KEY=$(_existing DEVINSIGHT_JWT_SIGNING_KEY || true)
if [[ -z "$DEVINSIGHT_JWT_SIGNING_KEY" ]]; then
  DEVINSIGHT_JWT_SIGNING_KEY=$(openssl rand -base64 48 | tr -d '\n')
fi
write_env DEVINSIGHT_JWT_SIGNING_KEY "$DEVINSIGHT_JWT_SIGNING_KEY"
say "Optional: an Anthropic API key enables AI feedback (billed per analysis). Press Enter to skip."
ask_secret DEVINSIGHT_ANTHROPIC_API_KEY "Anthropic API key:"
write_env DEVINSIGHT_ANTHROPIC_API_KEY "$DEVINSIGHT_ANTHROPIC_API_KEY"
pause

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Let GitHub Actions deploy to Azure (OIDC, no stored secret)"
say "Creates an Entra app registration trusted only for the 'production' environment of $REPO,"
say "with Contributor rights on $AZURE_RESOURCE_GROUP only."
# Each piece is created only if missing, so re-running repairs a partial earlier run.
AZURE_CLIENT_ID=$(az ad app list --display-name "github-devinsight-deploy" --query "[0].appId" -o tsv)
if [[ -z "$AZURE_CLIENT_ID" ]]; then
  AZURE_CLIENT_ID=$(az ad app create --display-name "github-devinsight-deploy" --query appId -o tsv)
fi
SP_OBJECT_ID=$(az ad sp list --filter "appId eq '$AZURE_CLIENT_ID'" --query "[0].id" -o tsv)
if [[ -z "$SP_OBJECT_ID" ]]; then
  SP_OBJECT_ID=$(az ad sp create --id "$AZURE_CLIENT_ID" --query id -o tsv)
fi
if [[ -z "$(az ad app federated-credential list --id "$AZURE_CLIENT_ID" --query "[?name=='github-production'].name" -o tsv)" ]]; then
  az ad app federated-credential create --id "$AZURE_CLIENT_ID" --output none --parameters "{
    \"name\": \"github-production\",
    \"issuer\": \"https://token.actions.githubusercontent.com\",
    \"subject\": \"repo:$REPO:environment:production\",
    \"audiences\": [\"api://AzureADTokenExchange\"]
  }"
fi
# A new service principal takes a while to replicate: assign by object id (no Graph lookup) and retry.
SCOPE="/subscriptions/$AZURE_SUBSCRIPTION_ID/resourceGroups/$AZURE_RESOURCE_GROUP"
if [[ -z "$(az role assignment list --assignee "$SP_OBJECT_ID" --scope "$SCOPE" --role Contributor --query "[0].id" -o tsv)" ]]; then
  for attempt in 1 2 3 4 5 6; do
    if az role assignment create --assignee-object-id "$SP_OBJECT_ID" --assignee-principal-type ServicePrincipal \
      --role Contributor --scope "$SCOPE" --output none; then
      break
    fi
    if [[ "$attempt" == 6 ]]; then
      warn "Could not grant Contributor on $AZURE_RESOURCE_GROUP; fix the error above and re-run the wizard."
      exit 1
    fi
    note "Waiting for the service principal to replicate (attempt $attempt of 6)..."
    sleep 20
  done
fi
printf '  %s✓%s Contributor on %s\n' "$GREEN" "$RESET" "$AZURE_RESOURCE_GROUP"
write_env AZURE_CLIENT_ID "$AZURE_CLIENT_ID"
set_var AZURE_CLIENT_ID "$AZURE_CLIENT_ID"
set_var AZURE_TENANT_ID "$AZURE_TENANT_ID"
set_var AZURE_SUBSCRIPTION_ID "$AZURE_SUBSCRIPTION_ID"
set_var AZURE_RESOURCE_GROUP "$AZURE_RESOURCE_GROUP"
pause

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Build the API image"
say "The deploy workflows run from 'main', so the .NET rewrite must be merged before this step."
if confirm "Is it merged? Start the deploy-api workflow (builds and pushes the image)?"; then
  gh workflow run deploy-api.yml --repo "$REPO" --ref main
  say "Follow it at https://github.com/$REPO/actions and wait for it to finish (about 5 minutes)."
fi
pause "Press Enter once deploy-api has finished"
step "Make the image pullable by Azure: Danger Zone > Change visibility > Public."
open_url "https://github.com/users/CMaintz/packages/container/devinsight-api/settings"
pause "Press Enter once the package is public"

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Deploy the infrastructure"
say "Creates the Container App (and PostgreSQL, if chosen) running the real image."
say "GitHub sign-in stays disabled until the next stage supplies the OAuth credentials."
DEVINSIGHT_GITHUB_CLIENT_ID=$(_existing DEVINSIGHT_GITHUB_CLIENT_ID || echo pending)
DEVINSIGHT_GITHUB_CLIENT_SECRET=$(_existing DEVINSIGHT_GITHUB_CLIENT_SECRET || echo pending)
if ! confirm "Create the Azure resources now (anything beyond the free grants is billed)?"; then
  exit 1
fi
deploy_infra "$IMAGE"
write_env DEVINSIGHT_API_URL "$API_URL"
set_var DEVINSIGHT_API_URL "$API_URL"
pause

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "GitHub OAuth App"
open_url "https://github.com/settings/applications/new"
step "Application name: DevInsight"
step "Homepage URL:     $FRONTEND_URL"
step "Callback URL:     $API_URL/api/auth/github/callback"
step "Leave 'Enable Device Flow' unchecked, then click Register application."
ask DEVINSIGHT_GITHUB_CLIENT_ID "Paste the Client ID:"
step "Click 'Generate a new client secret' and copy it (it is shown only once)."
ask_secret DEVINSIGHT_GITHUB_CLIENT_SECRET "Paste the client secret:"
write_env DEVINSIGHT_GITHUB_CLIENT_ID "$DEVINSIGHT_GITHUB_CLIENT_ID"
write_env DEVINSIGHT_GITHUB_CLIENT_SECRET "$DEVINSIGHT_GITHUB_CLIENT_SECRET"
pause

# ── 8 ─────────────────────────────────────────────────────────────────────
stage "Apply the OAuth credentials"
deploy_infra "$IMAGE"
# Changing only secret values creates no new revision and running replicas keep the old values,
# so start a new revision to make the credentials take effect now.
az extension add --name containerapp --upgrade --only-show-errors
az containerapp update --name ca-devinsight-api --resource-group "$AZURE_RESOURCE_GROUP" \
  --revision-suffix "oauth$(date +%s)" --output none
curl -fsS "$API_URL/health" >/dev/null && printf '  %s✓%s API is healthy\n' "$GREEN" "$RESET" \
  || warn "Health check failed (a cold start can take a minute); retry: curl $API_URL/health"
pause

# ── 9 ─────────────────────────────────────────────────────────────────────
stage "GitHub Pages"
say "Sets the Pages source of $REPO to 'GitHub Actions', then publishes the SPA."
if gh api "repos/$REPO/pages" >/dev/null 2>&1; then
  gh api -X PUT "repos/$REPO/pages" -f build_type=workflow >/dev/null
else
  gh api -X POST "repos/$REPO/pages" -f build_type=workflow >/dev/null
fi
printf '  %s✓%s Pages source: GitHub Actions\n' "$GREEN" "$RESET"
gh workflow run deploy-pages.yml --repo "$REPO" --ref main
say "Follow it at https://github.com/$REPO/actions"
step "Then open $FRONTEND_URL, sign in, import and analyse, and set your bio and LinkedIn in Settings."
pause

finish
