import { ChangeDetectionStrategy, Component, computed, input } from '@angular/core';
import { Feedback } from '../../core/models/api.models';
import { CATEGORY_LABELS } from '../format/metrics';

const SEVERITY_LABELS = { low: 'Low', medium: 'Medium', high: 'High' } as const;

/** One feedback card: strengths vs improvements, severity, category and an AI marker. */
@Component({
  selector: 'app-feedback-item',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <article
      class="fb"
      [class.fb--strength]="feedback().isStrength"
      [class]="'fb sev-' + feedback().severity"
    >
      <header class="fb__head">
        <span class="fb__icon" aria-hidden="true">{{ feedback().isStrength ? '✓' : '!' }}</span>
        <h4 class="fb__title">{{ feedback().title }}</h4>
      </header>
      <p class="fb__message">{{ feedback().message }}</p>
      <ul class="fb__tags" aria-label="Details">
        <li class="tag">{{ kind() }}</li>
        @if (!feedback().isStrength) {
          <li class="tag tag--sev">{{ severity() }} priority</li>
        }
        <li class="tag">{{ category() }}</li>
        @if (feedback().type === 'ai') {
          <li class="tag tag--ai" title="Generated by an AI model">AI</li>
        }
        @if (context()) {
          <li class="tag">{{ context() }}</li>
        }
      </ul>
    </article>
  `,
  styleUrl: './feedback-item.scss',
})
export class FeedbackItem {
  readonly feedback = input.required<Feedback>();
  /** Optional context such as the repository name. */
  readonly context = input('');

  protected readonly kind = computed(() =>
    this.feedback().isStrength ? 'Strength' : 'Improvement',
  );
  protected readonly severity = computed(() => SEVERITY_LABELS[this.feedback().severity]);
  protected readonly category = computed(() => CATEGORY_LABELS[this.feedback().category]);
}
